"""empty message

Revision ID: 6057f6aa390c
Revises: 
Create Date: 2019-07-13 15:37:41.088090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6057f6aa390c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('jersey', sa.Integer(), nullable=True),
    sa.Column('photoURL', sa.String(length=100), nullable=True),
    sa.Column('initialVal', sa.Integer(), nullable=True),
    sa.Column('updateDate', sa.DateTime(), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_name'), 'stock', ['name'], unique=False)
    op.create_index(op.f('ix_stock_team'), 'stock', ['team'], unique=False)
    op.create_table('projection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stockID', sa.Integer(), nullable=True),
    sa.Column('passingYards', sa.Float(), nullable=True),
    sa.Column('passingTDs', sa.Float(), nullable=True),
    sa.Column('passingInterceptions', sa.Float(), nullable=True),
    sa.Column('rushingAttempts', sa.Float(), nullable=True),
    sa.Column('rushingYards', sa.Float(), nullable=True),
    sa.Column('rushingTouchdowns', sa.Float(), nullable=True),
    sa.Column('receptions', sa.Float(), nullable=True),
    sa.Column('receivingYards', sa.Float(), nullable=True),
    sa.Column('receivingTDs', sa.Float(), nullable=True),
    sa.Column('fumblesLost', sa.Float(), nullable=True),
    sa.Column('puntReturnTDs', sa.Float(), nullable=True),
    sa.Column('kickReturnTDs', sa.Float(), nullable=True),
    sa.Column('twoPointConvertPasses', sa.Float(), nullable=True),
    sa.Column('twoPointConvertRuns', sa.Float(), nullable=True),
    sa.Column('twoPointConvertReceptions', sa.Float(), nullable=True),
    sa.Column('fantasyPoints', sa.Float(), nullable=True),
    sa.Column('fantasyPointsPPR', sa.Float(), nullable=True),
    sa.Column('updateDate', sa.DateTime(), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stockID'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projection')
    op.drop_index(op.f('ix_stock_team'), table_name='stock')
    op.drop_index(op.f('ix_stock_name'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
