"""empty message

Revision ID: 7fd62bb30b6a
Revises: a0b333c14c71
Create Date: 2019-07-11 14:17:09.325098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd62bb30b6a'
down_revision = 'a0b333c14c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projection', sa.Column('passingTDs', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projection', 'passingTDs')
    # ### end Alembic commands ###
